# Generated by Django 3.2.7 on 2021-10-08 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('active', models.BooleanField(default=True, help_text='Indica si el modelo está operativo', verbose_name='Activo')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('base_stats', models.JSONField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('evolutions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_pokemon_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
