# Generated by Django 3.2.7 on 2021-09-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
